RINGBUFFERDIR = $(shell echo ~/)GIT_RPO/simpleringbuffer 

RINGBUFFERCFILESRAW   = getrandom 
RINGBUFFERCPPFILESRAW = pointer shm Clock

RINGBUFFERCFILES = $(addprefix $(RINGBUFFERDIR), RINGBUFFERCFILESRAW)
RINGBUFFERCPPFILES = $(addprefix $(RINGBUFFERDIR), RINGBUFFERCPPFILESRAW)
